#!/usr/bin/env bash
# Generate git_version.inc with branch and commit hash
# Run before compiling the plugin

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT="${SCRIPT_DIR}/cstrike/addons/amxmodx/scripting/git_version.inc"

BRANCH=$(git -C "${SCRIPT_DIR}" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
COMMIT=$(git -C "${SCRIPT_DIR}" rev-parse --short HEAD 2>/dev/null || echo "unknown")

echo "// Auto-generated by gen_version.sh - do not edit" > "${OUTPUT}"
echo "#define GIT_PLUGIN_VERSION \"1.0.0-${BRANCH}.${COMMIT}\"" >> "${OUTPUT}"

echo "Generated ${OUTPUT}: GIT_PLUGIN_VERSION = 1.0.0-${BRANCH}.${COMMIT}"
